name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Install dependencies
        run: npm i && cd frontend && npm i && cd ../server && npm i
      - name: Autograde
        uses: education/autograding@v1